import { index, layout, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/index.tsx"),
  route("sign-in", "routes/sign-in.tsx"),
  route("household/join", "routes/household-join.tsx"),
  route("shared/shopping", "routes/shared-shopping-exchange.tsx"),
  route("shared/shopping/:shareId", "routes/shared-shopping.tsx"),
  layout("routes/app-layout.tsx", [
    route("recipes", "routes/recipes.tsx"),
    route("recipes/new", "routes/recipe-new.tsx"),
    route("recipes/import/:ingestionId", "routes/recipe-import-review.tsx"),
    route("recipes/:recipeId/edit", "routes/recipe-edit.tsx"),
    route("recipes/:recipeId", "routes/recipe-detail.tsx"),
    route("favorites", "routes/favorites.tsx"),
    route("plan", "routes/plan.tsx"),
    route("shopping", "routes/shopping.tsx"),
    route("settings", "routes/settings.tsx"),
  ]),
  route("api/v1/health", "routes/api.health.ts"),
  route("api/v1/recipes/search", "routes/api.recipes.search.ts"),
  route("api/v1/recipes/:recipeId", "routes/api.recipes.detail.ts"),
  route("api/v1/recipes/:recipeId/pdf", "routes/api.recipe.pdf.ts"),
  route("api/v1/recipe-ingestions", "routes/api.recipe-ingestions.ts"),
  route("api/v1/recipe-ingestions/:ingestionId", "routes/api.recipe-ingestion.ts"),
  route("api/v1/saved-searches", "routes/api.saved-searches.ts"),
  route("api/v1/saved-searches/:savedSearchId", "routes/api.saved-search.ts"),
  route("api/v1/meal-plans", "routes/api.meal-plans.ts"),
  route("api/v1/meal-plans/:planId/pdf", "routes/api.meal-plan.pdf.ts"),
  route("api/v1/meal-plans/:planId/combined.pdf", "routes/api.combined.pdf.ts"),
  route("api/v1/meal-plan-items/:itemId", "routes/api.meal-plan-item.ts"),
  route("api/v1/meal-plans/clone-previous", "routes/api.meal-plans.clone.ts"),
  route("api/v1/shopping-lists/generate", "routes/api.shopping.generate.ts"),
  route("api/v1/shopping-lists/latest", "routes/api.shopping.latest.ts"),
  route("api/v1/shopping-lists/:listId/pdf", "routes/api.shopping.pdf.ts"),
  route("api/v1/shopping-lists/:listId/shares", "routes/api.shopping.shares.ts"),
  route("api/v1/shopping-lists/:listId/shares/:shareId", "routes/api.shopping.share.ts"),
  route("api/v1/shopping-lists/:listId/email", "routes/api.shopping.email.ts"),
  route("api/v1/email-deliveries/:deliveryId", "routes/api.email-delivery.ts"),
  route("api/public/shopping/exchange", "routes/api.public.shopping.exchange.ts"),
  route("api/public/shopping/:shareId", "routes/api.public.shopping.ts"),
  route("api/public/shopping/:shareId/items/:itemId", "routes/api.public.shopping.item.ts"),
  route("api/public/shopping/logout", "routes/api.public.shopping.logout.ts"),
  route("api/public/household-invitations/exchange", "routes/api.public.household-invitation.exchange.ts"),
  route("api/v1/openapi.json", "routes/api.openapi.ts"),
  route("api/auth/*", "routes/api.auth.ts"),
  route("mcp", "routes/mcp.ts"),
] satisfies RouteConfig;
