import type { CombinedExportModel, MealPlanExportModel, RecipeExportModel, ShoppingListExportModel } from "./models";

export function escapeHtml(value: unknown): string {
  return String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character] ?? character);
}

const measurementLabel = (value: string) => value === "metric" ? "Metric (EU)" : value === "us" ? "US customary" : "Original units";

const styles = `
  :root { color: #17201b; font-family: Inter, ui-sans-serif, system-ui, -apple-system, sans-serif; }
  * { box-sizing: border-box; }
  body { margin: 0; font-size: 10pt; line-height: 1.42; }
  h1 { margin: 0 0 5mm; font-size: 23pt; line-height: 1.08; }
  h2 { margin: 0 0 3mm; font-size: 14pt; }
  p { margin: 0 0 3mm; }
  .document { padding: 13mm; }
  .meta { margin-bottom: 7mm; color: #58645d; }
  .tags { display: flex; flex-wrap: wrap; gap: 2mm; margin-bottom: 6mm; }
  .tag { padding: 1mm 2.2mm; border: .25mm solid #bcc7c0; border-radius: 1mm; font-size: 8pt; }
  .recipe-grid { display: grid; grid-template-columns: 38% 1fr; gap: 10mm; }
  ul, ol { margin: 0; padding-left: 6mm; }
  li { break-inside: avoid; margin-bottom: 2.5mm; }
  .ingredient { padding: 2.2mm 0; border-bottom: .2mm solid #dfe4e0; }
  .unresolved::after { content: " *"; color: #9c5b14; }
  .plan-table { width: 100%; border-collapse: collapse; table-layout: fixed; }
  .plan-table th, .plan-table td { padding: 2.5mm; border: .25mm solid #cdd5d0; vertical-align: top; }
  .plan-table th { background: #edf2ee; font-size: 8.5pt; text-align: left; }
  .plan-slot { width: 24mm; font-weight: 700; }
  .meal { margin-bottom: 2mm; padding: 2mm; background: #e3f0e8; break-inside: avoid; }
  .meal strong, .meal small { display: block; }
  .meal small { margin-top: 1mm; color: #647068; }
  .shopping-grid { columns: 2; column-gap: 10mm; }
  .shopping-item { min-height: 10mm; display: grid; grid-template-columns: 5mm minmax(0,1fr) auto; gap: 3mm; align-items: start; padding: 2.2mm 0; border-bottom: .2mm solid #dfe4e0; break-inside: avoid; }
  .checkbox { width: 4mm; height: 4mm; margin-top: .5mm; border: .45mm solid #68756d; }
  .checked .checkbox { background: #176b4d; box-shadow: inset 0 0 0 .8mm white; }
  .checked .item-name { color: #68756d; text-decoration: line-through; }
  .item-copy small { display: block; margin-top: .7mm; color: #68756d; font-size: 7.5pt; }
  .quantity { white-space: nowrap; font-weight: 700; }
  .section-break { break-before: page; }
  .footer-note { margin-top: 6mm; color: #68756d; font-size: 7.5pt; }
  @page { margin: 8mm; }
  @media screen { body { background: #e8ece9; } .document { width: min(1100px, calc(100% - 32px)); min-height: 90vh; margin: 16px auto; background: white; box-shadow: 0 8px 24px rgba(0,0,0,.12); } }
`;

function shell(title: string, body: string, landscape = false): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><style>${styles}${landscape ? "@page { size: landscape; }" : ""}</style></head><body>${body}</body></html>`;
}

function recipeBody(model: RecipeExportModel): string {
  return `<main class="document"><h1>${escapeHtml(model.title)}</h1><p class="meta">${model.servings === null ? "Yield not specified" : `${escapeHtml(model.servings)} servings`} &middot; ${measurementLabel(model.measurementSystem)}</p>${model.description ? `<p>${escapeHtml(model.description)}</p>` : ""}<div class="tags">${model.tags.map((tag) => `<span class="tag">${escapeHtml(tag)}</span>`).join("")}</div><div class="recipe-grid"><section><h2>Ingredients</h2><div>${model.ingredients.map((item) => `<div class="ingredient${item.unresolved ? " unresolved" : ""}">${escapeHtml(item.text)}</div>`).join("")}</div></section><section><h2>Method</h2><ol>${model.steps.map((step) => `<li>${escapeHtml(step)}</li>`).join("")}</ol></section></div><p class="footer-note">Generated by Tableplan on ${new Date().toISOString().slice(0, 10)}</p></main>`;
}

function mealPlanBody(model: MealPlanExportModel, sectionBreak = false): string {
  return `<main class="document${sectionBreak ? " section-break" : ""}"><h1>${escapeHtml(model.title)}</h1><p class="meta">${escapeHtml(model.startsOn)} to ${escapeHtml(model.endsOn)}</p><table class="plan-table"><thead><tr><th>Meal</th>${model.days.map((day) => `<th>${escapeHtml(day.label)}</th>`).join("")}</tr></thead><tbody>${model.slots.map((slot) => `<tr><td class="plan-slot">${escapeHtml(slot.label)}</td>${model.days.map((day) => `<td>${day.meals.filter((meal) => meal.slotId === slot.id).map((meal) => `<div class="meal"><strong>${escapeHtml(meal.recipeName)}</strong><small>${escapeHtml(meal.servings)} servings${meal.notes ? ` &middot; ${escapeHtml(meal.notes)}` : ""}</small></div>`).join("")}</td>`).join("")}</tr>`).join("")}</tbody></table><p class="footer-note">Generated by Tableplan on ${new Date().toISOString().slice(0, 10)}</p></main>`;
}

function shoppingBody(model: ShoppingListExportModel, sectionBreak = false): string {
  return `<main class="document${sectionBreak ? " section-break" : ""}"><h1>${escapeHtml(model.title)}</h1><p class="meta">${model.startsOn && model.endsOn ? `${escapeHtml(model.startsOn)} to ${escapeHtml(model.endsOn)} &middot; ` : ""}${measurementLabel(model.measurementSystem)} &middot; ${model.items.length} items</p><div class="shopping-grid">${model.items.map((item) => `<div class="shopping-item${item.checked ? " checked" : ""}"><span class="checkbox"></span><div class="item-copy"><strong class="item-name${item.unresolved ? " unresolved" : ""}">${escapeHtml(item.name)}</strong>${item.sources.length ? `<small>${item.sources.map(escapeHtml).join(", ")}</small>` : ""}</div><span class="quantity">${escapeHtml(item.quantity)}</span></div>`).join("")}</div><p class="footer-note">Generated by Tableplan on ${new Date().toISOString().slice(0, 10)}</p></main>`;
}

export function renderRecipeHtml(model: RecipeExportModel): string { return shell(model.title, recipeBody(model)); }
export function renderMealPlanHtml(model: MealPlanExportModel): string { return shell(model.title, mealPlanBody(model), true); }
export function renderShoppingListHtml(model: ShoppingListExportModel): string { return shell(model.title, shoppingBody(model)); }
export function renderCombinedHtml(model: CombinedExportModel): string { return shell(`${model.plan.title} and shopping list`, `${mealPlanBody(model.plan)}${shoppingBody(model.shoppingList, true)}`, true); }
